### SPECIES ---------------------------------------------

### GET request to find all species
GET http://localhost:9080/api/species/
###

### GET request to find species
GET http://localhost:9080/api/species/6614a2ee-96b8-4cae-ae18-61691d05834e
###

### POST request to create species
POST http://localhost:9080/api/species/
Content-Type: application/json

{
  "name": "New Species",
  "type": "NORMAL"
}
###

### PATCH request to update species
PATCH http://localhost:9080/api/species/6614a2ee-96b8-4cae-ae18-61691d05834e
Content-Type: application/json

{
  "name": "Updated Species Name",
  "type": "NORMAL",
  "increaseAttackPerLevel": 12
}

### DELETE request to delete species
DELETE http://localhost:9080/api/species/965830df-f75b-40dd-8200-1cb0a1be4d38
###
// ------------------------------------------------

### POKEMONS ---------------------------------------------

### GET request to find pokemons by species
GET http://localhost:9080/api/species/965830df-f75b-40dd-8200-1cb0a1be4d38/pokemons/
###

### GET request to find pokemons by species
GET http://localhost:9080/api/species/965830df-f75b-40dd-8200-1cb0a1be4d38/pokemons/70c51310-63e6-464c-ba13-5a7464cd311d
###

### POST request to create pokemon
POST http://localhost:9080/api/species/f7c3e1d2-3b6a-4f8e-9c2d-1e2f3a4b5c6d/pokemons/
Content-Type: application/json

{
  "name": "New Pokemon",
  "health": 35,
  "attack": 55,
  "defense": 40,
  "level": 5
}
###

### PATCH request to update pokemon
PATCH http://localhost:9080/api/species/f7c3e1d2-3b6a-4f8e-9c2d-1e2f3a4b5c6d/pokemons/70939f1c-fe5b-497c-968d-907b68d92bf6
Content-Type: application/json

{
  "name": "New Pokemon2",
  "health": 35,
  "attack": 55,
  "defense": 40,
  "level": 5
}

### DELETE request to delete pokemon
DELETE http://localhost:9080/api/species/f7c3e1d2-3b6a-4f8e-9c2d-1e2f3a4b5c6d/pokemons/70939f1c-fe5b-497c-968d-907b68d92bf6
###

// ------------------------------------------------


### USERS ---------------------------------------------

### POST request to create user
POST http://localhost:9080/api/users/register
Content-Type: application/json

{
  "username": "newuser",
  "email": "test@gmail.com",
  "password": "password123"
}
###

### GET request to find all users
GET http://localhost:9080/api/users/
###



### GET request to find user
GET http://localhost:9080/pokemon/api/users/aaf8b3ad-f935-4e77-a01e-718f338a37ca
###

### GET request to find user - not found
GET http://localhost:9080/pokemon/api/users/aaf8b3ad-f935-4e77-a01e-718f338a3769
###

### GET request to find user avatar
GET http://localhost:9080/pokemon/api/users/fea12d2a-d65a-49ce-9a3e-d6d5b31e0878/avatar
###

### Post user avatar.

POST http://localhost:9080/pokemon/api/users/fea12d2a-d65a-49ce-9a3e-d6d5b31e0878/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar1.png'

< avatars/avatar1.png
--boundary--
###


### Put user avatar.

PUT http://localhost:9080/pokemon/api/users/fea12d2a-d65a-49ce-9a3e-d6d5b31e0878/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar3.png'

< avatars/avatar3.png
--boundary--
###

### Delete user avatar
DELETE http://localhost:9080/pokemon/api/users/fea12d2a-d65a-49ce-9a3e-d6d5b31e0878/avatar
###